// UserAuthentication
export const USERNAME_INPUT_CHANGE = 'USERNAME_INPUT_CHANGE'
export const PASSWORD_INPUT_CHANGE = 'PASSWORD_INPUT_CHANGE'
export const LOGIN_SUBMIT = 'LOGIN_SUBMIT'
export const LOGIN_SUBMIT_SUCCESS = 'LOGIN_SUBMIT_PENDING'
export const LOGIN_SUBMIT_FAILURE = 'LOGIN_SUBMIT_FULFILLED'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE'


// Timeline
export const REQUEST_DATA_FROM_TOKEN = 'REQUEST_DATA_FROM_TOKEN'
export const REQUEST_DATA_FROM_TOKEN_SUCCESS = 'REQUEST_DATA_FROM_TOKEN_SUCCESS'
export const REQUEST_DATA_FROM_TOKEN_FAILURE = 'REQUEST_DATA_FROM_TOKEN_FAILURE'
