// UserAuthentication
export const USERNAME_INPUT_CHANGE = 'USERNAME_INPUT_CHANGE'
export const PASSWORD_INPUT_CHANGE = 'PASSWORD_INPUT_CHANGE'
export const LOGIN_SUBMIT = 'LOGIN_SUBMIT'
export const LOGIN_SUBMIT_SUCCESS = 'LOGIN_SUBMIT_PENDING'
export const LOGIN_SUBMIT_FAILURE = 'LOGIN_SUBMIT_FULFILLED'
